libraries:                                      # Library mappings must have a colon (:) placed after them
    Movies:
        metadata_path:
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/Movies.yml
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/MovieCharts.yml
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/Studios.yml
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/MovieCharts.yml
    TV Shows:
        metadata_path:
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/ShowCharts.yml
          - url: https://raw.githubusercontent.com/dezerving/plex/main/pmm-configs/dezerving/Networks.yml
settings:                                       # Can be individually specified per library as well
    cache: true
    cache_expiration: 60
    asset_directory: config/assets
    asset_folders: true
    assets_for_all: false
    sync_mode: append
    show_unmanaged: true
    show_filtered: false
    show_missing: true
    save_missing: true
    run_again_delay: 2
plex:                                           # Can be individually specified per library as well
    url: https://plex.kishanspatel.com
    token: SpjiZZtpk7mypmLzg1xw
    timeout: 60
    clean_bundles: false
    empty_trash: false
    optimize: false
tmdb:
    apikey: 254e1331483f569c79193a34be611410
    language: en
tautulli:                                       # Can be individually specified per library as well
    url: https://tautulli.kishanspatel.com
    apikey: 45b9655f88844a44845c10826059dca9
radarr:                                         # Can be individually specified per library as well
    url: https://dezerving.lw986.usbx.me/radarr/
    token: 0ce5c723e04f447daf8d390e522778b7
    version: v3
    add: false
    root_folder_path: /hom33/dezerving/mnt1/gcrypt/Movies
    monitor: true
    availability: announced
    quality_profile: HD-1080p
    tag:
    search: false
sonarr:                                         # Can be individually specified per library as well
    url: https://dezerving.lw986.usbx.me/sonarr/
    token: 767afa88cbc047ac9862e9f0de9a5791
    version: v3
    add: false
    root_folder_path: “/home33/dezerving/mnt1/gcrypt/TV Shows”
    monitor: all
    quality_profile: HD-720p/1080p
    language_profile: English
    series_type: standard
    season_folder: true
    tag:
    search: false
    cutoff_search: false
omdb:
    apikey: d44a0e07
trakt:
    client_id: 0fb3357d1e299683bf03184e595ea0b4d6159303b28fcf9be19898b0bb7a76fc
    client_secret: 2bf02e12069edf3151157dbd73bc4651b6516941bf527752ef870369ca1f8c15
    authorization:
        access_token: 5a9a02a165fcb49ecc1aa7e9096a00ccc6331e8e9754aaf5508b2d36a4259194
        token_type: Bearer
        expires_in: 7889237
        refresh_token: aa4f014c672d61f303ee658333ea6be88c5e2e24911b6f532735a7a59cf34717
        scope: public
        created_at: 1625953644
